import localFont from "next/font/local";
import "./globals.css";
import Provider from "@/component/AuthProvider/Provider";
import Head from 'next/head'; // Import the Head component



// Load local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata
export const metadata = {
  title: "Edu-Explorer",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Add the favicon to the head */}
      <Head>
        <link rel="icon" href="src\app\assets\Study.png" />
        <title>Edu-Explorer</title> {/* Optional: Set the page title */}
      </Head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
